name: multiplatform_login_screen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  flutter_form_builder: ^9.0.0
  flutter_secure_storage: ^8.0.0
  form_builder_validators: ^9.0.0
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
