import 'package:flutter/material.dart';

ThemeData lightTheme() {
  return ThemeData(
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFA04ACF),
      onPrimary: Color(0xFFAA9EFF),
      primaryContainer: Color(0xFFA04ACF),
      onPrimaryContainer: Color(0xFF861BC0),
      secondary: Color(0xFF74565F),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFF59607A),
      onSecondaryContainer: Color(0xFF59607A),
      tertiary: Color(0xFF7C5635),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDCC1),
      onTertiaryContainer: Color(0xFF2E1500),
      error: Color(0xFFC80005),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF2A083D),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A1B),
      surfaceVariant: Color(0xFFF2DDE1),
      onSurfaceVariant: Color(0xFF514347),
      outline: Color(0xFF59607A),
      onInverseSurface: Color(0xFFFAEEEF),
      inverseSurface: Color(0xFF352F30),
      inversePrimary: Color(0xFFFFB1C8),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFB90063),
      outlineVariant: Color(0xFFD5C2C6),
      scrim: Color(0xFF000000),
    ),
    fontFamily: 'Comfortaa',
    textTheme: const TextTheme(
        headlineLarge: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.bold,
          fontSize: 39,
        ),
        headlineMedium: TextStyle(
          color: Colors.black,
          fontSize: 16,
          fontWeight: FontWeight.bold,
        ),
        displayLarge: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.bold,
          height: 1.6,
          fontSize: 20,
        ),
        displayMedium: TextStyle(
          color: Color(0xFF59607A),
          height: 1.5,
          fontSize: 15,
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.normal,
          height: 1.6,
          fontSize: 13,
        ),
        labelSmall: TextStyle(
          letterSpacing: 0.5,
          color: Color(0xFFF03D4B),
          decoration: TextDecoration.underline,
          fontSize: 12,
          fontWeight: FontWeight.w400,
        ),
        labelMedium: TextStyle(
          color: Color(0xFFF03D4B),
          fontSize: 15,
          fontWeight: FontWeight.w500,
        )),
  );
}

ThemeData darkTheme() {
  return ThemeData(
    useMaterial3: true,
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB1C8),
      onPrimary: Color(0xFF650033),
      primaryContainer: Color(0xFF8E004A),
      onPrimaryContainer: Color(0xFFFFD9E2),
      secondary: Color(0xFFE3BDC6),
      onSecondary: Color(0xFF422931),
      secondaryContainer: Color(0xFF5A3F47),
      onSecondaryContainer: Color(0xFFFFD9E2),
      tertiary: Color(0xFFEFBD94),
      onTertiary: Color(0xFF48290C),
      tertiaryContainer: Color(0xFF623F20),
      onTertiaryContainer: Color(0xFFFFDCC1),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A1B),
      onBackground: Color(0xFFEBE0E1),
      surface: Color(0xFF201A1B),
      onSurface: Color(0xFFEBE0E1),
      surfaceVariant: Color(0xFF514347),
      onSurfaceVariant: Color(0xFFD5C2C6),
      outline: Color(0xFF9E8C90),
      onInverseSurface: Color(0xFF201A1B),
      inverseSurface: Color(0xFFEBE0E1),
      inversePrimary: Color(0xFFB90063),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFFFB1C8),
      outlineVariant: Color(0xFF514347),
      scrim: Color(0xFF000000),
    ),
    fontFamily: 'Comfortaa',
    textTheme: const TextTheme(
      headlineLarge: TextStyle(
        color: Colors.white,
        fontWeight: FontWeight.bold,
        fontSize: 39,
      ),
      displayLarge: TextStyle(
        color: Colors.white,
        fontWeight: FontWeight.normal,
        height: 1.6,
        fontSize: 20,
      ),
      displayMedium: TextStyle(
        color: Colors.white,
        fontWeight: FontWeight.normal,
        height: 1.6,
        fontSize: 16,
      ),
      displaySmall: TextStyle(
        color: Colors.white,
        fontWeight: FontWeight.normal,
        height: 1.6,
        fontSize: 13,
      ),
    ),
  );
}
